import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import './globals.css'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className + ' bg-slate-900'}>
        <header>
          <nav>
            <ul className="flex justify-center gap-5 text-slate-50 text-2xl py-5">
              <li className="hover:text-sky-500"><Link href="/">Home</Link></li>
              <li className="hover:text-sky-500"><Link href='/about-me'>Sobre mi</Link></li>
              <li className="hover:text-sky-500"><Link href='/services'>Servicios</Link></li>
              <li className="hover:text-sky-500"><Link href='/blog'>Blog</Link></li>
              <li className="hover:text-sky-500"><Link href='/contacs'>Contactos</Link></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
